### ISSUE TITLE
TypeError: super() takes at least 1 argument (0 given) in constructor of SuffixTree

### ISSUE THREAD

**Issue by himito** [cartoonist/suffixtree#1]
Hi!,

I'm trying to build a suffix tree,  but I got an error when I use 
`st = SuffixTree("ababababaabb")` in python 2.7.

<img width="639" alt="capture d ecran 2016-09-01 a 15 57 02" src="https://cloud.githubusercontent.com/assets/181677/18170057/1958d63e-705d-11e6-939a-6ce794852dbc.png">

Thank you in advance.

**Comment by cartoonist** [comment]
Hi,

The code is written in Python 3 and it uses some features of the language that cannot be run in Python 2.7. For this case, in Python 3, the `super` method can be call without argument. This is not the case in Python 2.7.

**Comment by himito** [comment]
Hi,

Thank you for your answer :). Then, I think that you should configure the package in the PyPI to install only with pip3 (it is only available for pip2) :).

**Comment by cartoonist** [comment]
Thanks a lot for letting me know that. I will fix. Really appreciated.
